DROP DATABASE IF EXISTS LUMINAR;
CREATE DATABASE LUMINAR;
USE LUMINAR;


CREATE TABLE CANDIDATO(
ID INT PRIMARY KEY NOT NULL auto_increment,
NOMBRE varchar(30),
APELLIDOS VARCHAR(30),
CORREO VARCHAR(50),
CONTRA VARCHAR(20)
);

CREATE TABLE RECLUTADOR(
ID INT PRIMARY KEY NOT null auto_increment,
NOMBREEM varchar(30),
RAZON VARCHAR(30),
RFC long,
NOMBREPER VARCHAR(30),
APELLIDOS VARCHAR(50),
CONTRA VARCHAR(20)
);